---
title: "Read CSV files with Cochrane results"
author: "ses"
date: "5/18/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Setup

```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H',
  fig.asp = 0.618,
  fig.width = 5,
  fig.cap = "", 
  fig.path = "",
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.show = "hold")
```


```{r}
library(tidyverse)
library(here)
library(glue)
```


# Constants


```{r}
reviewer_selected <- "np"
data_path <- paste0(here(),"/output/", reviewer_selected)
data_path
```



# Read all CSV files


```{r}
csv_files <- list.files(path = data_path,
           pattern = ".csv")
```

```{r}
length(csv_files)
```



# Exclude non-relevant files


```{r}
relevant_pattern <- "^\\d+\\.CD\\d+\\.pub\\d\\.csv$"
#relevant_pattern2 <- "^\\d+\\.CD"

```


```{r}
csv_files2 <- 
  csv_files %>% 
  keep(.p = str_detect(., relevant_pattern))
```


# Check

```{r}
length(csv_files2)
```


```{r}
#file_to_look_for <- "14651858.CD004123.pub4.csv"

#any(csv_files2 == file_to_look_for)
```


# Add path back in


```{r}
csv_files3 <-
  csv_files2 %>% 
  paste0(data_path, "/", .)
```


```{r}
head(csv_files3)
```

```{r}
length(csv_files3)
```


# Build df

```{r}
parse_csv <- function(filename) {
  
  output <- read_csv(filename)
  
  if (!is_integer(output$n_participants_studies))
    output$n_participants_studies <- parse_integer(as.character(output$n_participants_studies),
                                                   na = c("", "NA", NA))
  
  return(output)
}
```

Check:

```{r}
out <- parse_csv(csv_files3[1])
str(out$n_participants_studies)
parse_integer(as.character(NA))
```



```{r}
reviews_output <- 
csv_files3 %>% 
  map_dfr(parse_csv, .id = "filename")
```


```{r}
reviews_output %>% 
  head()
```

```{r}
dim(reviews_output)
```


```{r}
str(reviews_output$n_participants_studies)
```


# Save to disk


```{r}
full_path <- glue("{data_path}/reviews_output_machine_{reviewer_selected}.xlsx")
full_path

writexl::write_xlsx(reviews_output,
                    path = full_path)
```

